import re

def is_number(s):
	try:
		int(s)
		return True
	except ValueError:
		return False

def is_line_valid(line):
	return not is_number(line) and not previous_was_number and content != ''

fo = open('autogenerated.srt', 'r')
content = fo.readlines()
fo.close()
content = [x.strip() for x in content]

actual_content = []
previous_was_number = False

for line in content:
	if is_line_valid(line):
		actual_content.append(line + '\n')
	if is_number(line):
		previous_was_number = True
	else:
		previous_was_number = False

fw = open('autofiltered.txt', 'w')
regex = re.compile(r"<[\w,\/,#,=,\", ]*>", re.IGNORECASE)
for line in actual_content:
    line = regex.sub('', line)
    fw.write(line)
    print line

fw.close()